import Head from 'next/head'
import { Fragment } from 'react/cjs/react.production.min'

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div id='content'>
    </div>
    </Fragment>
  )
}
